---
- name: Configure tmux
  block:
    - name: Make tmux git directory safe
      command: "git config --global --add safe.directory {{ target_dir }}/.tmux"
      check_mode: no
    - name: Download pretty tmux from git
      git:
        repo: "https://github.com/gpakosz/.tmux.git"
        dest: "{{ target_dir }}/.tmux"
    - name: Copy local tmux config to home dir
      command: cp .tmux/.tmux.conf.local .
      args:
        chdir: "{{ target_dir }}"
    - name: Create tmux config symlink
      command: ln -s -f .tmux/.tmux.conf
      args:
        chdir: "{{ target_dir }}"
